// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'xfirebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATYU8uGZbga8ADtdu9YKaEKx7iqZqv42c',
    appId: '1:379613229041:web:049058c8cba13fb13c9e50',
    messagingSenderId: '379613229041',
    projectId: 'growductive',
    authDomain: 'growductive.firebaseapp.com',
    storageBucket: 'growductive.firebasestorage.app',
    measurementId: 'G-5SYW6T4JGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr2Xcpi5l4mTrhrtHzfqg5Lpu4Dw0Wiig',
    appId: '1:379613229041:android:e4c4d7e5bf718dc73c9e50',
    messagingSenderId: '379613229041',
    projectId: 'growductive',
    storageBucket: 'growductive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr2Xcpi5l4mTrhrtHzfqg5Lpu4Dw0Wiig',
    appId: '1:379613229041:ios:PLACEHOLDER_IOS',
    messagingSenderId: '379613229041',
    projectId: 'growductive',
    storageBucket: 'growductive.firebasestorage.app',
    iosBundleId: 'com.example.growductive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr2Xcpi5l4mTrhrtHzfqg5Lpu4Dw0Wiig',
    appId: '1:379613229041:ios:PLACEHOLDER_MACOS',
    messagingSenderId: '379613229041',
    projectId: 'growductive',
    storageBucket: 'growductive.firebasestorage.app',
    iosBundleId: 'com.example.growductive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATYU8uGZbga8ADtdu9YKaEKx7iqZqv42c',
    appId: '1:379613229041:web:049058c8cba13fb13c9e50',
    messagingSenderId: '379613229041',
    projectId: 'growductive',
    authDomain: 'growductive.firebaseapp.com',
    storageBucket: 'growductive.firebasestorage.app',
    measurementId: 'G-5SYW6T4JGZ',
  );
}
